version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_cnt
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_vol:/var/jenkins_home
volumes:
  jenkins_vol:
